### ISSUE TITLE
Access to a Shared Folder

### ISSUE THREAD

**Issue by manuparra** [vishal-biyani/fission-spec-example#1]
Hi @vishal-biyani !
I'm wondering if I can use fission spec to access from the function to a storage space by changing `.yaml` specification, for example adding the next:

```
apiVersion: v1
kind: Pod
...
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim`
      ...
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage

```

What is the way to do it in fission with spec option?
Regards.
